import type { FashionAdvisor } from '@/types';

export const FASHION_ADVISORS: FashionAdvisor[] = [
  {
    id: 'advisor-1',
    name: 'Priya Sharma',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
    specialization: ['Wedding Sarees', 'Kanjivaram Silk', 'Traditional Styling'],
    experience: 8,
    rating: 4.9,
    totalConsultations: 1250,
    languages: ['English', 'Hindi', 'Tamil'],
    availability: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    bio: 'Expert in traditional South Indian silk sarees with 8 years of experience in bridal styling. Specialized in color coordination and occasion-based saree selection.',
  },
  {
    id: 'advisor-2',
    name: 'Anjali Mehta',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop',
    specialization: ['Cotton Sarees', 'Casual Wear', 'Contemporary Draping'],
    experience: 6,
    rating: 4.8,
    totalConsultations: 980,
    languages: ['English', 'Hindi', 'Gujarati'],
    availability: ['tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    bio: 'Passionate about handloom cotton sarees and sustainable fashion. Helps customers find comfortable yet elegant sarees for daily wear and casual occasions.',
  },
  {
    id: 'advisor-3',
    name: 'Lakshmi Iyer',
    image: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=400&h=400&fit=crop',
    specialization: ['Festive Collection', 'Color Consultation', 'Artisan Stories'],
    experience: 10,
    rating: 5.0,
    totalConsultations: 1850,
    languages: ['English', 'Hindi', 'Malayalam', 'Kannada'],
    availability: ['monday', 'wednesday', 'thursday', 'friday', 'saturday'],
    bio: 'Senior stylist with deep knowledge of regional handloom traditions. Specializes in festive sarees and has personally visited artisan communities across India.',
  },
  {
    id: 'advisor-4',
    name: 'Divya Reddy',
    image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop',
    specialization: ['Luxury Sarees', 'Designer Draping', 'Premium Fabrics'],
    experience: 7,
    rating: 4.9,
    totalConsultations: 1120,
    languages: ['English', 'Hindi', 'Telugu'],
    availability: ['monday', 'tuesday', 'thursday', 'friday', 'saturday'],
    bio: 'Luxury saree consultant with expertise in high-end silk and designer collections. Perfect for special occasions and premium saree selections.',
  },
];

export const TIME_SLOTS = [
  '10:00 AM',
  '10:30 AM',
  '11:00 AM',
  '11:30 AM',
  '12:00 PM',
  '12:30 PM',
  '02:00 PM',
  '02:30 PM',
  '03:00 PM',
  '03:30 PM',
  '04:00 PM',
  '04:30 PM',
  '05:00 PM',
  '05:30 PM',
  '06:00 PM',
];
