import type { Saree } from '@/types';
import img1 from '@/assets/img7.jpg';
import img2 from '@/assets/img6.jpg';
import img3 from '@/assets/img6.jpg';
import img4 from '@/assets/img6.jpg';
import img5 from '@/assets/img8.jpg';
import img6 from '@/assets/img9.jpg';
import img7 from '@/assets/img10.jpg';
import img8 from '@/assets/img11.jpg';
import img9 from '@/assets/img12.jpg';
import img10 from '@/assets/img13.jpg';
import img11 from '@/assets/img14.jpg';
import img12 from '@/assets/img15.jpg';
import img13 from '@/assets/img17.jpg';

export const SAREES: Saree[] = [
  {
    id: '1',
    name: 'Royal Kanjivaram Silk Saree',
    price: 18999,
    originalPrice: 24999,
    fabric: 'Silk',
    occasion: ['Wedding'],
    color: 'Red',
    images: [
      img1,
      img2,
      img3,
    ],
    description: 'Exquisite Kanjivaram silk saree with intricate zari work and traditional temple border. Perfect for weddings and grand celebrations.',
    weavingTechnique: 'Traditional Kanjivaram weaving with pure zari threads',
    artisanDetails: 'Handcrafted by master weavers from Kanchipuram, Tamil Nadu',
    careInstructions: 'Dry clean only. Store in a cool, dry place wrapped in muslin cloth.',
    length: '6.3 meters with 0.8m blouse piece',
    blousePiece: true,
    stock: 5,
    rating: 4.8,
    reviews: 127,
    featured: true,
    bestSeller: true,
  },
  {
    id: '2',
    name: 'Banarasi Silk Wedding Saree',
    price: 22499,
    originalPrice: 28999,
    fabric: 'Silk',
    occasion: ['Wedding'],
    color: 'Gold',
    images: [
      img4,
      img5,
    ],
    description: 'Luxurious Banarasi silk saree with gold zari brocade work and Mughal-inspired motifs.',
    weavingTechnique: 'Banarasi brocade with Kadwa technique',
    artisanDetails: 'Crafted by skilled artisans from Varanasi, Uttar Pradesh',
    careInstructions: 'Dry clean recommended. Avoid direct sunlight.',
    length: '6.3 meters with blouse piece',
    blousePiece: true,
    stock: 3,
    rating: 4.9,
    reviews: 89,
    featured: true,
    newArrival: true,
    bestSeller: true,
  },
  {
    id: '3',
    name: 'Elegant Cotton Handloom Saree',
    price: 3499,
    originalPrice: 4999,
    fabric: 'Cotton',
    occasion: ['Casual'],
    color: 'Blue',
    images: [
      img6,
      img7,
    ],
    description: 'Soft cotton handloom saree perfect for daily wear with traditional block print borders.',
    weavingTechnique: 'Handloom cotton weaving',
    artisanDetails: 'Made by women weavers from West Bengal',
    careInstructions: 'Hand wash or gentle machine wash. Iron on medium heat.',
    length: '6 meters with blouse piece',
    blousePiece: true,
    stock: 15,
    rating: 4.6,
    reviews: 234,
    newArrival: true,
  },
  {
    id: '4',
    name: 'Festive Tussar Silk Saree',
    price: 8999,
    originalPrice: 12999,
    fabric: 'Silk',
    occasion: ['Festive'],
    color: 'Green',
    images: [
      img8,
      img9,
    ],
    description: 'Beautiful Tussar silk saree with golden border, ideal for festivals and celebrations.',
    weavingTechnique: 'Tussar silk handloom weaving',
    artisanDetails: 'Handwoven by tribal artisans from Jharkhand',
    careInstructions: 'Dry clean only. Store away from moisture.',
    length: '6.25 meters with blouse piece',
    blousePiece: true,
    stock: 8,
    rating: 4.7,
    reviews: 156,
    bestSeller: true,
    newArrival: true,

  },
  {
    id: '5',
    name: 'Pure Khadi Cotton Saree',
    price: 2999,
    fabric: 'Khadi',
    occasion: ['Casual'],
    color: 'White',
    images: [
      img10,
    ],
    description: 'Authentic khadi cotton saree promoting sustainable fashion and supporting rural artisans.',
    weavingTechnique: 'Hand-spun and handwoven khadi',
    artisanDetails: 'Crafted by khadi cooperatives in Gujarat',
    careInstructions: 'Hand wash with mild detergent. Line dry in shade.',
    length: '6 meters with blouse piece',
    blousePiece: true,
    stock: 20,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: '6',
    name: 'Designer Linen Saree',
    price: 4999,
    originalPrice: 6999,
    fabric: 'Linen',
    occasion: ['Party'],
    color: 'Pink',
    images: [
      img11,
    ],
    description: 'Contemporary linen saree with modern prints and lightweight comfort.',
    weavingTechnique: 'Linen handloom with digital print',
    artisanDetails: 'Designed and woven in Kerala',
    careInstructions: 'Machine washable. Iron while slightly damp.',
    length: '6 meters with blouse piece',
    blousePiece: true,
    stock: 12,
    rating: 4.4,
    reviews: 67,
    newArrival: true,
  },
  {
    id: '7',
    name: 'Chanderi Silk Cotton Saree',
    price: 6499,
    originalPrice: 8999,
    fabric: 'Silk',
    occasion: ['Festive'],
    color: 'Purple',
    images: [
      img12,
    ],
    description: 'Delicate Chanderi saree with silk cotton blend and traditional motifs.',
    weavingTechnique: 'Chanderi handloom weaving',
    artisanDetails: 'Woven by artisans from Chanderi, Madhya Pradesh',
    careInstructions: 'Dry clean preferred. Gentle hand wash acceptable.',
    length: '6.25 meters with blouse piece',
    blousePiece: true,
    stock: 7,
    rating: 4.8,
    reviews: 142,
    featured: true,
    
  },
  {
    id: '8',
    name: 'Patola Silk Wedding Saree',
    price: 45999,
    originalPrice: 59999,
    fabric: 'Silk',
    occasion: ['Wedding'],
    color: 'Multicolor',
    images: [
      img13,
    ],
    description: 'Rare double ikat Patola silk saree - a masterpiece of Indian textile heritage.',
    weavingTechnique: 'Double ikat Patola weaving',
    artisanDetails: 'Created by master weavers from Patan, Gujarat',
    careInstructions: 'Professional dry clean only. Handle with care.',
    length: '6.5 meters with blouse piece',
    blousePiece: true,
    stock: 2,
    rating: 5.0,
    reviews: 45,
    featured: true,
    bestSeller: true,
  },
];
